export const themes = {
  default: {
    label: 'Default',
    description: "The tool's original blue/red palette.",
    vars: {
      '--ts-font-family': 'system-ui, sans-serif',
      '--ts-body-bg': 'transparent',
      '--ts-text-color': '#1a1a1a',
      '--ts-hint-color': '#555',
      '--ts-border-color': '#ccc',
      '--ts-success-color': '#2f7a3f',
      '--ts-error-color': '#a13d3d',
      '--ts-room-fill': '#f5f5f5',
      '--ts-room-stroke': '#333',
      '--ts-diagram-border': '#ddd',
      '--ts-table-fill': '#7aa6c2',
      '--ts-table-stroke': '#2c4a5e',
      '--ts-table-hover-fill': '#5c8aa8',
      '--ts-table-shadow-color': '#2c4a5e',
      '--ts-obstacle-fill': '#d98c8c',
      '--ts-obstacle-stroke': '#a13d3d',
      '--ts-obstacle-label-color': '#6b2323',
      '--ts-obstacle-row-border': '#eee',
    },
  },
  midnight: {
    label: 'Midnight',
    description: 'Dark mode, for embedding in a dark-themed site.',
    vars: {
      '--ts-font-family': 'system-ui, sans-serif',
      '--ts-body-bg': '#15161d',
      '--ts-text-color': '#e8e8ec',
      '--ts-hint-color': '#a0a0ab',
      '--ts-border-color': '#3a3a44',
      '--ts-success-color': '#5fd97b',
      '--ts-error-color': '#ff7a7a',
      '--ts-room-fill': '#20212b',
      '--ts-room-stroke': '#4a4b58',
      '--ts-diagram-border': '#3a3a44',
      '--ts-table-fill': '#5b8ab0',
      '--ts-table-stroke': '#bcd6ea',
      '--ts-table-hover-fill': '#79a6cc',
      '--ts-table-shadow-color': '#5b8ab0',
      '--ts-obstacle-fill': '#a85c5c',
      '--ts-obstacle-stroke': '#e39a9a',
      '--ts-obstacle-label-color': '#f3caca',
      '--ts-obstacle-row-border': '#3a3a44',
    },
  },
  blush: {
    label: 'Blush',
    description: 'Soft pink and gold, wedding-venue feel.',
    vars: {
      '--ts-font-family': 'Georgia, "Times New Roman", serif',
      '--ts-body-bg': '#fffaf8',
      '--ts-text-color': '#4a3b3b',
      '--ts-hint-color': '#8a7373',
      '--ts-border-color': '#e5c9c9',
      '--ts-success-color': '#7a8f5c',
      '--ts-error-color': '#b5566e',
      '--ts-room-fill': '#fdf6f3',
      '--ts-room-stroke': '#d9b8b8',
      '--ts-diagram-border': '#e5c9c9',
      '--ts-table-fill': '#e3b8c2',
      '--ts-table-stroke': '#a8677a',
      '--ts-table-hover-fill': '#d99fae',
      '--ts-table-shadow-color': '#c98fa0',
      '--ts-obstacle-fill': '#cbb992',
      '--ts-obstacle-stroke': '#a68f5c',
      '--ts-obstacle-label-color': '#6b5a33',
      '--ts-obstacle-row-border': '#eeddd6',
    },
  },
  slate: {
    label: 'Slate',
    description: 'Neutral gray, corporate or conference feel.',
    vars: {
      '--ts-font-family': '"Segoe UI", Roboto, Helvetica, Arial, sans-serif',
      '--ts-body-bg': '#eceef0',
      '--ts-text-color': '#26282b',
      '--ts-hint-color': '#6b7178',
      '--ts-border-color': '#d3d6da',
      '--ts-success-color': '#2f7a3f',
      '--ts-error-color': '#b3413c',
      '--ts-room-fill': '#f4f5f6',
      '--ts-room-stroke': '#8a9099',
      '--ts-diagram-border': '#d3d6da',
      '--ts-table-fill': '#8b98a8',
      '--ts-table-stroke': '#3f4750',
      '--ts-table-hover-fill': '#6f7f92',
      '--ts-table-shadow-color': '#5b6672',
      '--ts-obstacle-fill': '#c9a26a',
      '--ts-obstacle-stroke': '#8f6b34',
      '--ts-obstacle-label-color': '#5c4520',
      '--ts-obstacle-row-border': '#e2e4e7',
    },
  },
};

export const themeList = Object.entries(themes).map(([id, theme]) => ({ id, ...theme }));
